title: B2X Studio
remote_theme: broccolini/swiss
description: Turning identity up to 11.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://b2x.studio" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: web # the GitHub repo name for your project
github_username: b2x-studio
permalink: /:title

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: azureandchill

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: yellow

# Build settings
# markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag