title: "b2x.studio"
# description: "b2x studio"
author_name: "jpda"

remote_theme: sparanoid/almace-scaffolding
#url: https://jpda.dev
#permalink: /:title
#timezone: America/New_York
#mathjax: false

#appInsights: true
#appInsightsKey: "aa50374c-4629-4ab3-a058-5bb4d8bb1924"
#fontawesome: false
#resume_url: "img/file-pngrepo-com.png"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at
  
  # Development mode
#
# Development mode is disabled on production build by default, we've enabled it
# in `_config.dev.yml` for local development, so most of the time you don't
# need to change it.
#
# Default:      false
dev:            false

# Site name
#
# Default:      Almace Scaffolding
name:           B2X Studio

# Site short name
#
# Currently only used by Chrome Web App manifest, can be anything you like.
# You can also just use your `name` for `name_short` if it is short enough
#
# For example:
# - name:       Almace Scaffolding
# - name_short: AMSF
#
# or:
# - name:       Sparanoid Group
# - name_short: Sparanoid
#
# Default:      AMSF
name_short:     B2XS

# Site description
#
# Will be used in the document meta and Atom feed subtitle
#
# Default:      Super-fast Jekyll framework
description:    B2X Studio

# Base URL
#
# This is useful when I need to build site in a subdirectory (like
# GitHub Pages for Projects), it provides a specific URL prefix, for example, if
# the production site URL is https://sparanoid.com/my-project/, set `baseurl` to
# `/my-project`, without trailing slash.
#
# Default:      ""
# baseurl:        /lab/amsf

# Flatten base
#
# This is useful when you generate your static site for GitHub Pages. By default
# the generated pages will have full hierarchy with `baseurl` you defined. This
# behavior will causes wrong URLs when using GitHub Pages under `docs/`. So
# enable this option if you're using GitHub Pages.
#
# Default:      false
flatten_base:   false

# CSS path used in templates
#
# Default:      /assets
assets:         /assets

# Feed URL
#
# Define your main feed URL, this will be only used in your templates
#
# Default:      /feed.xml
feed:           /feed.xml

# Site full URL
#
# Used in atom feed, sitemap, Twitter Cards, and etc. I should use absolute full
# URLs for these fields
#
# Default:      https://sparanoid.com
url:            https://b2x.studio

# Media assets URL
#
# Media assets URL are used in posts, without trailing slash. ie.
# `<img src="{{ site.file }}/image.png">`. In the most cases this URL should be
# powered by a CDN provider
# Note: you should avoid protocol-free (ie. //cdn.mysite.tld) address here
# because Twitter Cards doesn't work well with protocol-free assets when AMSF
# grabs the first image of your post as post featured image.
#
# Default:      https://d349cztnlupsuf.cloudfront.net
file:           https://d349cztnlupsuf.cloudfront.net

# Download files URL
#
# Download files URL are used in posts, ie.
# href="{{ site.download }}/package.zip", this should also be a CDN link just
# like `site.file`. There're no notable differences in `site.file` and
# `site.download`, I just use the one for post images and the other for large
# download files. That's it. Remove or ignore this if you don't need it.
#
# Default:      https://d1bmx7s6749k4k.cloudfront.net
download:       https://d1bmx7s6749k4k.cloudfront.net

# Colors
#
# Used by Safari mask-icon, Chrome Web App theme color
colors:
  theme:        "#ff00b4"
  background:   "#fff"

# Service Worker Precache
service_worker:
  enabled:      true
  max_size:     120000
  files:
    - "**/*.{css,html,jpg,gif,png,svg,woff,woff2}"
    - "**/js/**.js"

# Google Analytics tracking code
google_analytics:
  enabled:      false
  id:           UA-xxxxxxx
  url:          https://www.google-analytics.com/analytics.js

# Site Twitter account handle
twitter:        azureandchill

# Twitter Cards large images
#
# Use summary card with large image for Twitter Cards, require theme support
#
# Default:      true
tc_large_image: true

# Force UTF-8 encoding
#
# Enable this will simply add <meta charset="utf-8"> to the head of your pages
#
# Default:      true
force_utf_8:    true

# Generator credits
#
# Show or hide generator credits, require theme support
#
# Default:      true
credits:        true

# Custom records in robots.txt
#
# For example:
# robots:
#   - "User-agent: *"
#   - "Disallow: /ajax/"
#   - "Disallow: /@async"
#   - "Disallow: /log/"
#
# Default:      "User-agent: *"
# robots:         "User-agent: *"
